
# Create a new cart
# @name createCart
POST http://localhost:3000/carts
Content-Type: application/json

{
  "customerId": "customer-123"
}

###
# Add item to cart

@cartId = {{createCart.response.body.cartId}}
POST http://localhost:3000/carts/{{cartId}}/items
Content-Type: application/json

{
  "productId": "product-123",
  "quantity": 5
}

###
# Add item 2 to cart
POST http://localhost:3000/carts/{{cartId}}/items
Content-Type: application/json

{
  "productId": "product-456",
  "quantity": 4
}

###

# Get cart by ID
GET http://localhost:3000/carts/{{cartId}}

###
# Get non-existing cart
GET http://localhost:3000/carts/00000000-0000-0000-0000-000000000000

###
# Checkout cart
# @name checkout
POST http://localhost:3000/carts/{{cartId}}/checkout
Content-Type: application/json

{
  "shippingAddress": {
    "street": "123 Main St",
    "city": "Anytown",
    "stateOrProvince": "CA",
    "postalCode": "12345",
    "country": "USA"
  }
}

###
@orderId = {{checkout.response.body.orderId}}
POST http://localhost:3000/payments
Content-Type: application/json

{
  "orderId": "{{orderId}}",
  "amount": 10000,
  "currency": "USD"
}