
GET http://localhost:3000/orders

###

# Create a new cart
# @name createCart
POST http://localhost:3000/carts
Content-Type: application/json

{
  "customerId": "customer-123"
}

###
# Add item to cart

@cartId = {{createCart.response.body.cartId}}
POST http://localhost:3000/carts/{{cartId}}/items
Content-Type: application/json

{
  "productId": "product-456",
  "quantity": 2
}

###

# Get cart by ID
GET http://localhost:3000/carts/{{cartId}}

###
# Get non-existing cart
GET http://localhost:3000/carts/00000000-0000-0000-0000-000000000000